### PR TITLE
Monologue v3.0.0-dev1

### PR DESCRIPTION
**Pull request by atomic-junky**
I think the work we've done so far has enabled us to create a first pre-release for Monologue 3.0. The current version is certainly better and more complete than 2.3. It would also allow us to get feedback, bug reports and maybe even new contributors. (about twenty people "discover" Monologue every week on itch.io.)

By the way, I've started making a documentation for Monologue on a new [repo](https://github.com/atomic-junky/Monologue-docs).
Perhaps we could set up an organization.

### CODE REVIEW

**Review by RailKill — APPROVED** [review]
Previously NodeRandom isn't working properly and can crash. I did a quick fix although a little messy, it should work fine now. Maybe you can do one final test and if everything seems fine then the pre-release build is good to go 👍

**Comment by atomic-junky** [comment]
Idk why the build doesn't work 😭

**Comment by RailKill** [comment]
hmm can't really see what's the problem, seems like godot crashed while exporting the .pck for windows in the github action logs. there were some import and wine warnings/errors but not sure if it is related to the crash. i've enabled the verbose flag in export.yml, try triggering the export again and maybe it might tell us more

**Comment by atomic-junky** [comment]
If I've understood correctly, it's a RID leak and it's a bug from Godot.

**Comment by atomic-junky** [comment]
It worked! I think it's because of one of the addons (probably GdUnit)

**Pull request merged**
