### PR TITLE
Resolve #28 GraphNode rework

### LINKED ISSUE #28: GraphNode rework
All GraphNodes are hardcoded and all their fields are implemented by hand, even when it's for very simple things.

The problem is that the slightest change can very easily break everything, and is a pain in the ass every time.
The aim would therefore be to make the GraphNode code as simple as possible and put everything in the MonologueGraphNode class.

Currently, the way these changes have been made is that control nodes with the prefix "Field_" automatically become fields, which will be registered and monitored automatically.
The value of these nodes is automatically associated with a key in the name following the "Field_" prefix.

For example :
A LineEdit node with the name "Field_Sentence" will be linked to the "Sentence" field, and when loaded will take the value of the "Sentence" key. Each time the LineEdit changes, the value of "Sentence" will be updated. There's no need to specify that the "Sentence" key exists, as it will be created automatically.

### PR DESCRIPTION
**Pull request by RailKill**
With our combined efforts, I think we're pretty much done with the graph node rework and can be merged to main. It should be able to open/convert old JSON files and Test should work as normal. Lemme know if you find something broken and need me to fix.

Some UI stuff were left out, which is best finalized by [feature/ui-redesign](https://github.com/atomic-junky/Monologue/tree/feature/ui-redesign):
- In this PR, graph node selector does not have icons for all the new nodes yet.
- In this PR, the Add menu at the Header does not show all the new nodes yet.

## Summary by Sourcery

Rework the graph node system to introduce new node types and enhance existing functionalities. Implement a new property management system for graph nodes and improve the test execution framework to handle flaky tests with retry logic. Update the HTML report generation to provide a more detailed and visually appealing output. Fix compatibility issues with Godot 4.4 and ensure proper handling of parameterized test cases.

New Features:
- Introduce a new `NodeConverter` class to convert v2.x node data into v3.x node data for loading old projects.
- Add new node types such as `AudioNode`, `BackgroundNode`, `SetterNode`, `WaitNode`, and `RerouteNode` to enhance the graph node functionalities.
- Implement a new `MonologueField` class to represent UI controls for editing graph node properties.
- Add support for handling flaky tests with retry logic and marking them as flaky if they pass after retries.

Bug Fixes:
- Fix issues with the `GdUnitSceneRunner` to ensure proper simulation of input events and scene interactions.
- Resolve compatibility issues with Godot 4.4 by updating error patterns and handling new script error formats.
- Correct the handling of parameterized test cases to ensure proper execution and reporting of test results.

Enhancements:
- Refactor the `GdUnitHtmlReport` to improve the structure and presentation of test reports, including a new CSS for styling.
- Improve the `GdUnitExecutionContext` to better manage test execution states and statistics, including support for flaky tests.
- Enhance the `MonologueGraphNode` class to support dynamic property management and UI updates.
- Update the `GdUnitTestSuiteScanner` to streamline the parsing and detection of test suites and test cases.

Documentation:
- Update documentation to reflect changes in node types and new features introduced in the graph node system.
- Revise user-facing documentation to include information on handling flaky tests and the new retry logic.

Tests:
- Add unit tests for new node types such as `ActionNode`, `OptionNode`, and `SentenceNode` to ensure correct functionality.
- Implement tests for the `NodeConverter` to verify the conversion of v2.x node data to v3.x format.

### CODE REVIEW

**Comment by atomic-junky** [comment]
All these changes were really necessary! Thank you so much for taking the time to do all this.
Before we merge this PR, I wanted to discuss a few things I've been thinking about.

First, I think we can change a bit the way id is generated. Ids are too long and such a level of complexity is not useful. When you want to check that ids are similar, especially with option ids, it immediately becomes very complicated. I think we could simply shorten them from “c0a1241f-cd61-4d5c-ab6a-33ea72ed1535” to “c0a1241f”. Or we could simply use another algorithm to generate these ids.

Second, I think we need to review the way variables and characters work and are defined (not with this PR). If we want to do something more permissive, we should perhaps separate variables and characters from the RootNode and take advantage of this to add new functionalities. But my biggest question is how characters are passed from one file to another. At the moment, you'd have to redefine everything in each file, and it's really laborious.

And finally, I think OptionNodes and ChoiceNodes need to be reworked too (not necessarily for this PR either). In my opinion, having OptionNodes that can be dissociated from ChoiceNodes would make it possible to do more things (I've made a wonderful diagram on Paint to illustrate my idea).
image

Otherwise, changing the DiceRollNode to a RandomNode that could have more than 2 outputs could be a simple and interesting change.

And thank you again for all your hard work!

**Comment by atomic-junky** [comment]
I've made some changes to NodeDiceRoll (it's now NodeRandom) but I'm having some issues making each outputs editable.
Can you check it out ?

**Comment by RailKill** [comment]
@atomic-junky I took a quick look and implemented a small fix. The node is not fully functional yet but it should give you an idea on how to proceed. Basically, it didn't work because it only looked at the list size, that's why all the items keep resetting to `100 / size`. There was no logic to redistribute weights based on the newly input value.

After the fix, `add_output()` for new items will redistribute by list size, but changes to individual field in `MonologueRandomOutput.gd` will redistribute by the newly changed value.

**Review by atomic-junky — COMMENTED** [review]
As it's here, I think the branch is complete. I'll leave it to you to decide whether or not to merge, depending on whether or not we need to change, fix or add features or whatever.

**Review by atomic-junky — APPROVED** [review]
*I forgot to approve*
There is just the NodeBackground, which is not yet fully supported by MonologueProcess, but it does not create any issues.

**Pull request merged**
