### PR TITLE
Native File Dialogue

### PR DESCRIPTION
**Pull request by Jeremi360**
So this chnage open/new file to use just Godot's FileDialog if native flag,
this way you gets native FileDialog and cross-platform app using the same code.
Here is opening json in Mologue on Linux :grin: 
 
monologue-linux-native

### CODE REVIEW

**Comment by atomic-junky** [comment]
Thank you so much, it's really nice of you to have made these changes! But my recent files appear with their full path. I don't know if that was done on purpose.
If not, can you fix it? If not, I can.
image

**Comment by Jeremi360** [comment]
> Thank you so much, it's really nice of you to have made these changes! But my recent files appear with their full path. I don't know if that was done on purpose. If not, can you fix it? If not, I can. image

Yes, it wasn't done on purpose, you should add some comments to your code.
So before my changes I did't even realzie that you have *Recent files* option,
As I was changing code I just saw that you was removing some text from file path,
and I thought that it could break crossplaftorm, as I wasn't sure what your remove and why.

Sorry but is hard to get a grasp of almost 500 lines of code in one file with out comments. 
It may seams like having one big script that keep all stuff is good, but not is isn't
I try to keep my scripts as small as possible.

**Comment by atomic-junky** [comment]
Ok, I understand, I did this (it only changes the button text). What do you think?
image

**Comment by Jeremi360** [comment]
> Ok, I understand, I did this (it only changes the button text). What do you think? image

Looks good, I will soon check it on linux, to be sure it dosen't break anything.

**Comment by Jeremi360** [comment]
@atomic-junky Just fixed it with last commit:
image

**Comment by atomic-junky** [comment]
It didn't work on Windows because it wasn't the right character string to split. So I tried to do something that should work for all OS and any type of path

**Comment by Jeremi360** [comment]
@atomic-junky My bad is it easy to mistake `\` with `/`.
Yhea it works under linux you can make it a bit simpler, as in godot docs:
> If either param begin or param end are negative, they will be relative to the end of the array (i.e. arr.slice(0, -2) is a shorthand for arr.slice(0, arr.size() - 2)).

So I just commited this little change :arrow_up: and use `join_path()` to make path look correct for native OS.
image

**Comment by atomic-junky** [comment]
Where did you commit these changes? I don't see any new commits

**Comment by Jeremi360** [comment]
@atomic-junky I think this is beacouse you closed PR before I send them so you will not see it in this PR: https://github.com/atomic-junky/Monologue/compare/main...Jeremi360:Monologue:native-file-dialogue

**Pull request merged**
